# Generated by Django 2.0.5 on 2020-07-04 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstapp',
            name='Contact',
            field=models.IntegerField(default=0),
        ),
    ]
