# Generated by Django 2.0.5 on 2020-07-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1app', '0002_firstapp_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstapp',
            name='Address',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='firstapp',
            name='Name',
            field=models.CharField(default='NULL', max_length=30),
        ),
    ]
